# -*- coding: utf-8 -*-
import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from insert_tp39 import NEW

NEW += '                    <div class="sec-title">Pattern Recognition Triggers</div>\n'
NEW += '                    <div class="info-box" style="line-height:1.75">\n'
NEW += '                        <strong>Linguistic Triggers:</strong><br>\n'
NEW += '                        &bull; "Count integers in [L, R] satisfying [property on digits]" &rarr; Stage 1 digit DP; f(R) &minus; f(L&minus;1); property determines extra state<br>\n'
NEW += '                        &bull; "How many numbers from 1 to N have [digit sum / count / pattern]" &rarr; Stage 2; extra dim = accumulated property (digit sum, count of specific digit)<br>\n'
NEW += '                        &bull; "Count n-digit numbers where [adjacency / ordering between consecutive digits]" &rarr; Stage 2; add prev_digit<br>\n'
NEW += '                        &bull; "Digits form [specific set / all unique / pandigital]" &rarr; Stage 3 bitmask digit DP; extra dim = bitmask of used digits<br>\n'
NEW += '                        &bull; "Numbers &le; N divisible by K with additional digit constraint" &rarr; Stage 3; value_mod_K AND additional state simultaneously; check state size before coding<br><br>\n'
NEW += '                        <strong>Structural Triggers:</strong><br>\n'
NEW += '                        &bull; Range [L, R] given with L, R &le; 10^18 and property is about individual digits &rarr; digit DP is the ONLY feasible approach; brute force is impossible<br>\n'
NEW += '                        &bull; Property defined RECURSIVELY on digit decomposition ("divisible by its own digits") &rarr; digit DP with dynamic modulus; precompute modulus space (lcm(1..9) = 2520)<br>\n'
NEW += '                        &bull; "Strings in [s1, s2]" with character-pattern constraint &rarr; string digit DP; characters are "digits"; tight applies lexicographically<br><br>\n'
NEW += '                        <strong>Constraint Triggers:</strong><br>\n'
NEW += '                        &bull; N &le; 10^18 (18 decimal digits) AND property on digit structure &rarr; digit DP is the intended solution<br>\n'
NEW += '                        &bull; n &le; 10^9 but represents NUMBER OF DIGITS &rarr; matrix exponentiation; recurrence is linear; O(states&sup3; log n)<br><br>\n'
NEW += '                        <strong>Anti-Triggers:</strong><br>\n'
NEW += '                        &bull; "Find the n-th lexicographically smallest number" &rarr; NOT direct digit DP &rarr; binary search on count function (f(x) uses digit DP internally) + greedy descent<br>\n'
NEW += '                        &bull; "Count integers with exactly K prime factors in [L, R]" &rarr; NOT digit DP &rarr; number-theoretic sieve; factorisation is not a digit property<br>\n'
NEW += '                        &bull; "Sum of all divisors of all integers in [1, N]" &rarr; NOT digit DP &rarr; Dirichlet hyperbola method; divisor sum is multiplicative\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Decision Framework</div>\n'
NEW += '                    <div class="info-box">\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0;font-size:.78rem"><code>Q1: Does the problem ask for a COUNT (or SUM) over integers in [L, R]\n'
NEW += '    where R can be up to 10^18?\n'
NEW += '  YES: Digit DP is the primary candidate. Continue to Q2.\n'
NEW += '  NO:  If R <= 10^6: brute force/sieve. If R <= 10^9: math formula.\n'
NEW += '\n'
NEW += 'Q2: Is the property defined ENTIRELY by digits (decimal, binary, base-b),\n'
NEW += '    independently of arithmetic properties?\n'
NEW += '  YES: Digit DP applies directly. Continue.\n'
NEW += '  NO:  Can the property be REDUCED to a digit property?\n'
NEW += '       "divisible by K" = track value mod K = digit DP with mod state.\n'
NEW += '\n'
NEW += 'Q3: What info must be CARRIED from left to right?\n'
NEW += '    (Defines extra state dimensions beyond pos and tight)\n'
NEW += '  Nothing:               (pos, tight).           Stage 1. O(18*2).\n'
NEW += '  Previous digit:        (pos, tight, prev).     Stage 2. O(18*2*10).\n'
NEW += '  Running sum/count:     (pos,tight,leading,sum).Stage 2. O(18*2*2*maxS).\n'
NEW += '  Bitmask used digits:   (pos,tight,leading,mask)Stage 3. O(18*2*2*1024).\n'
NEW += '  Value mod K:           (pos, tight, mod).      Stage 2-3. O(18*2*K).\n'
NEW += '  Multiple simult props: Stage 3. Product of all state sizes.\n'
NEW += '  Two tight flags:       Stage 4. state * 4.\n'
NEW += '\n'
NEW += 'Q4: Does the problem LOOK like digit DP without saying so?\n'
NEW += '    ("count strings in [s1, s2]", "count pairs (a,b) with a XOR b <= N",\n'
NEW += '     "count x <= N with some bit property")\n'
NEW += '  YES: Stage 4. Identify "digits" (bits, chars), "tight" (lex bound),\n'
NEW += '       extra state. Apply standard framework.\n'
NEW += '\n'
NEW += 'Q5: Is O(digits * state_space) too slow?\n'
NEW += '    (n = digit count up to 10^18, or K up to 10^6)\n'
NEW += '  YES: Stage 5:\n'
NEW += '       - Linear recurrence + huge n: matrix exponentiation.\n'
NEW += '       - Large K (mod K): meet in the middle (split at digit n/2).\n'
NEW += '       - State space explosion: look for compression\n'
NEW += '         (lcm(1..9)=2520 for "divisible by own digits").</code></pre>\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">When This Technique Breaks</div>\n'
NEW += '                    <div class="warn-box" style="line-height:1.75">\n'
NEW += '                        &bull; <strong>[Stage 1] Using digit DP when range is small (&le; 10&#8310;):</strong> Non-trivial implementation overhead. For small ranges, sieve or brute force is faster to write and less bug-prone. Fix: use digit DP ONLY when N &gt; 10&#8310; or property is hard to enumerate directly.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Missing leading-zero flag, counting 0-padded shorts as valid:</strong> Without leading flag, "007" is treated as 3-digit starting with 0, polluting bitmasks and adjacency checks. Fix: maintain leading = (all digits placed are 0). When leading=true, skip digit constraint.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Caching tight=true across different bounds:</strong> tight=true depends on SPECIFIC upper bound. Running f(R) and f(L&minus;1) in same memo table contaminates results. Fix: two separate memo tables, OR only memoise tight=false (tight=true re-explored; only n positions).<br>\n'
NEW += '                        &bull; <strong>[Stage 3] State explosion from large K (mod K with K up to 10&#8310;):</strong> 18 &times; 2 &times; K = 36M overflows memory. Fix: meet-in-the-middle &mdash; split digits in half; enumerate (prefix_mod, count) and (suffix_mod, count); join via hashmap in O(n/2 &times; K).<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Incorrect two-tight-flag transitions:</strong> When both tight_lo and tight_hi active, valid d &isin; [lo_digit if tight_lo else 0, hi_digit if tight_hi else 9]. Candidates forget to CLIP the lower bound. Fix: next_tight_lo = tight_lo AND (d == lo_digit); next_tight_hi = tight_hi AND (d == hi_digit).<br>\n'
NEW += '                        &bull; <strong>[Stage 4] Applying digit DP for K-th valid number (construction):</strong> Digit DP counts; it does not construct. Fix: use digit DP as count function INSIDE binary search or greedy construction &mdash; try digits 0..9 in order, count completions, subtract until remainder found.<br>\n'
NEW += '                        &bull; <strong>[Stage 5] Not precomputing powers of 10 for sum DP:</strong> Contribution = d &times; 10^remaining &times; sub_count. Recomputing 10^remaining inflates constants. Fix: precompute pow10[0..18] before DFS.\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Proof of Correctness Skeleton</div>\n'
NEW += '                    <div class="core-box">\n'
NEW += '                        <strong>Stage 1 &mdash; Counting Integers &le; N with No Digit 4</strong><br>\n'
NEW += '                        <em>Claim:</em> solve(pos=0, tight=true) counts all integers in [0, N] with no digit 4.<br>\n'
NEW += '                        <em>Proof:</em> (1) <em>Completeness:</em> every x &le; N is enumerated; if x[pos] &lt; N[pos], subsequent positions are free (tight=false); if x[pos] = N[pos], tight remains true. (2) <em>No over-counting:</em> DFS tree has no cycles; each root-to-leaf path = one integer. (3) <em>Tight correctness:</em> tight=false allows any digit; tight=true allows only 0..N[pos] &mdash; exactly enforces x &le; N. (4) <em>Memoisation validity:</em> dp[pos][tight=false] is independent of prefix (prefix already strictly below). &#9633;<br><br>\n'
NEW += '                        <strong>Stage 2 &mdash; Leading Zero Correctness in Bitmask Digit DP</strong><br>\n'
NEW += '                        <em>Claim:</em> With leading flag, bitmask captures only digits of the NUMBER (not leading zeros).<br>\n'
NEW += '                        <em>Proof sketch:</em> When leading=true and d=0: number hasn\'t started; bitmask NOT updated with bit 0. When leading=true and d&gt;0: leading flips to false; bit d set. From this point, all subsequent digits (including 0) update mask. Therefore bitmask at completion contains exactly digits in x\'s significant representation. &#9633;<br><br>\n'
NEW += '                        <strong>Stage 3 &mdash; Two-Tight-Flag Correctness</strong><br>\n'
NEW += '                        <em>Claim:</em> Two-tight-flag DP (tight_lo for &ge; L, tight_hi for &le; R) counts integers in [L, R].<br>\n'
NEW += '                        <em>Proof sketch:</em> <em>Invariant:</em> at every pos, if tight_lo still true, prefix equals L\'s prefix exactly; if tight_hi still true, prefix equals R\'s prefix exactly. <em>Valid range:</em> d &isin; [lo_digit if tight_lo else 0, hi_digit if tight_hi else 9]. At terminal pos=n: number satisfies x &ge; L AND x &le; R. By induction on n &minus; pos, sub-problem count is correct. &#9633;\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Implementation Pitfalls (Code-Level)</div>\n'
NEW += '                    <div class="warn-box">\n'
NEW += '                        <strong>Bug 1 &mdash; Caching tight=true across different bounds</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>@lru_cache(maxsize=None)\ndef dp(pos, tight):\n    # BUG: tight=True cached globally; different N reuses stale results\n# FIX: clear cache between calls, OR only cache tight=False:\ndef dp(pos, tight):\n    if not tight and pos in memo: return memo[pos]\n    result = compute(pos, tight)\n    if not tight: memo[pos] = result\n    return result</code></pre><br>\n'
NEW += '                        <strong>Bug 2 &mdash; Leading zero sets bit 0 in bitmask</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>next_mask = mask | (1 &lt;&lt; d)  # BUG: sets bit 0 when d=0 and still leading\n# FIX:\nnext_leading = leading and (d == 0)\nnext_mask = mask if next_leading else (mask | (1 &lt;&lt; d))</code></pre><br>\n'
NEW += '                        <strong>Bug 3 &mdash; Off-by-one: f(L) instead of f(L-1)</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>answer = f(R) - f(L)      # BUG: subtracts L itself if L satisfies P\nanswer = f(R) - f(L - 1)  # FIX</code></pre><br>\n'
NEW += '                        <strong>Bug 4 &mdash; L-1 underflow at L=0</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>answer = f(R) - (f(L - 1) if L &gt; 0 else 0)  # FIX</code></pre><br>\n'
NEW += '                        <strong>Bug 5 &mdash; Digit array built LSB-first</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code># BUG: digits in LSB order; DP processes MSB first\nwhile n &gt; 0: digits.append(n % 10); n //= 10\n# FIX: reverse, or just:\ndigits = [int(c) for c in str(n)]</code></pre><br>\n'
NEW += '                        <strong>Bug 6 &mdash; Value mod K using digit-sum recurrence</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>next_mod = (current_mod + digit) % K        # BUG: digit-sum mod K\nnext_mod = (current_mod * 10 + digit) % K  # FIX: NUMBER value mod K</code></pre><br>\n'
NEW += '                        <strong>Bug 7 &mdash; LCM state not compressed (for "divisible by own digits")</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code># BUG: treating LCM as raw int grows unbounded\n# FIX: LCM of digits USED SO FAR; max = lcm(1..9) = 2520\n# Precompute 48 divisors of 2520; map each to an index 0..47\nnext_digit_lcm = lcm(current_digit_lcm, digit) if digit != 0 else current_digit_lcm\n# State uses lcm_index, not raw LCM</code></pre><br>\n'
NEW += '                        <strong>Bug 8 &mdash; Two-tight-flag: lower bound not clamped</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>for d in range(0, hi_limit + 1):      # BUG: starts from 0 when tight_lo is active\n# FIX:\nlo_limit = digits_lo[pos] if tight_lo else 0\nhi_limit = digits_hi[pos] if tight_hi else 9\nfor d in range(lo_limit, hi_limit + 1):\n    next_tight_lo = tight_lo and (d == digits_lo[pos])\n    next_tight_hi = tight_hi and (d == digits_hi[pos])</code></pre><br>\n'
NEW += '                        <strong>Bug 9 &mdash; Matrix exp: wrong initial vector (allowing 0 as first digit)</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>initial = [1] * 10          # BUG: includes numbers starting with 0\ninitial = [0] + [1] * 9    # FIX: first digit in {1..9}</code></pre><br>\n'
NEW += '                        <strong>Bug 10 &mdash; Sum DP: wrong positional contribution formula</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>total_sum += d * pow10[remaining]  # BUG: missing sub_count multiplier\n# FIX:\n(sub_count, sub_sum) = dp(pos + 1, ...)\ntotal_sum += sub_sum + d * pow10[remaining] * sub_count\ntotal_count += sub_count</code></pre>\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Red Flags / Common Mistakes</div>\n'
NEW += '                    <div class="warn-box" style="line-height:1.75">\n'
NEW += '                        &bull; <strong>[Stage 1] Not using f(R) &minus; f(L&minus;1) and encoding both bounds in one DP:</strong> Beginners build a two-tight-flag DP when f(R) &minus; f(L&minus;1) suffices. Correct model for 95% of problems: define f(x); answer = f(R) &minus; f(L&minus;1). Only use two tight flags when bounds are given as strings or must be processed simultaneously.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Confusing "digit sum mod K" with "value mod K":</strong> Recurrences differ completely. Digit sum: next = (current + d) % K &mdash; linear. Number value: next = (current &times; 10 + d) % K &mdash; polynomial. Mixing gives wrong answers silently.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Omitting leading_zero flag when constraint involves digit 0:</strong> Without the flag, "007" contributes two 0s to digit count or sets bit 0 in bitmask. Any constraint involving digit 0 requires leading_zero; include by default.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Building state tuple without verifying state space fits memory:</strong> 18 &times; 2 &times; 2 &times; 10&#8310; = 72M entries &times; 8 bytes = 576 MB. Before coding, multiply all dimensions. If &gt; 10&#8311;, seek compression (LCM, meet-in-middle, smarter encoding).<br>\n'
NEW += '                        &bull; <strong>[Stage 4] Missing digit DP applicability for string-counting problems:</strong> Strings over lexicographic range [s1, s2] with char-level constraints ARE digit DP. "Digits" = characters; "tight" = lexicographic; upper bound = s2. Substitution is lossless.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Not precomputing digit array:</strong> Repeatedly calling str(n)[pos] or n // 10^pos % 10 inside memoised DFS inflates constants and introduces subtle bugs. Precompute digits = [int(c) for c in str(N)].<br>\n'
NEW += '                        &bull; <strong>[Stage 5] Standard DP when n (digit count) is ~10^18:</strong> O(n) states is infeasible. When n is a COUNT of digits (not the number), recurrence is linear &mdash; use matrix exponentiation in O(|S|&sup3; log n).\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Interviewer Follow-Up Questions</div>\n'
NEW += '                    <div class="tbl-wrap"><table>\n'
NEW += '                        <thead><tr><th>#</th><th>Stage Push</th><th>Question</th><th>Intended Answer Direction</th></tr></thead>\n'
NEW += '                        <tbody>\n'
NEW += '                        <tr><td class="num-cell">1</td><td>Stage 2</td><td>"Your solution counts integers &le; N with digit sum divisible by K. What if K changes per query, with Q queries up to 10&#8309;?"</td><td>Each query re-runs DP with K as state dim; O(18 &times; 2 &times; K) per query. Better: since digit_sum &le; 162, track ALL residues at once in one pass. Total O(18 &times; 162) per query regardless of K.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">2</td><td>Stage 2</td><td>"What if the constraint changes from \'digit sum divisible by K\' to \'digit sum is a perfect square\'?"</td><td>digit_sum runs 0..162 (9&times;18). At terminal, check if digit_sum is perfect square (precompute &#123;0,1,4,9,...,144&#125;). Zero code change to framework &mdash; only terminal acceptance changes. Emphasises plug-and-play nature.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">3</td><td>Stage 3</td><td>"Extend to: count integers &le; N where digit sum is divisible by K AND the number is a palindrome."</td><td>Two INDEPENDENT properties. Add palindrome_half tracking OR use outside-in palindrome construction. Modular constraint adds sum_mod_K; palindrome constraint handled by fixing digit n&minus;1&minus;pos = digit pos. State = (half_pos, tight, leading, sum_mod_K).</td></tr>\n'
NEW += '                        <tr><td class="num-cell">4</td><td>Stage 3</td><td>"How to compute the SUM of integers in [L, R] with digit sum &le; K, not just the count?"</td><td>DP returns (count, value_sum) tuple. Contribution of d at pos = d &times; 10^remaining &times; sub_count. Precompute pow10. Both count and sum updated in same DFS. Formula: total_sum += d &times; pow10[remaining] &times; sub_count + sub_sum.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">5</td><td>Stage 4</td><td>"Given string s, count same-length strings lex &le; s, no two identical adjacent chars, no char appearing &gt; K times."</td><td>Digit DP on strings: tight is lexicographic. State = (pos, tight, prev_char, freq). For K=1: bitmask over 26 chars. For K&le;2: per-char counts. Framework identical to integer digit DP; "digits" are chars; "base" is alphabet size.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">6</td><td>Stage 4</td><td>"Count integers in [L, R] that are both palindromes AND divisible by 7."</td><td>Combine outside-in palindrome construction with value mod 7 tracking. Each palindrome digit at position i contributes d &times; (10^i + 10^(n&minus;1&minus;i)) mod 7. Precompute positional weights mod 7. State = (half_pos, tight, leading, value_mod_7).</td></tr>\n'
NEW += '                        <tr><td class="num-cell">7</td><td>Stage 5</td><td>"Your digit DP is O(18 &times; 2 &times; 10 &times; K). What if K = 10&#8313; + 7?"</td><td>18 &times; 2 &times; 10&#8313; is impossible. Meet-in-the-middle: split at digit 9. Enumerate all (prefix_mod, count) pairs and (suffix_mod, count) pairs. Total: (prefix &times; 10&#8313; + suffix) mod K = 0 &rarr; suffix_mod = (&minus;prefix &times; 10&#8313;) mod K. Join via hashmap. For K this large, often problem has extra structure &mdash; use number-theoretic counting instead.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">8</td><td>Stage 5</td><td>"Count n-digit numbers (n &le; 10^18) with no two adjacent equal digits."</td><td>Custom Problem 2. Build 10&times;10 matrix T where T[i][j] = 1 if i &ne; j else 0. Initial v[d] = 1 for d &isin; &#123;1..9&#125;, v[0] = 0. Answer = sum(T^(n&minus;1) &times; v). O(10&sup3; log n) &asymp; 60,000 multiplications.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">9</td><td>Beyond Stage 5</td><td>"Online stream of queries (L_i, R_i). Each asks count in [L_i, R_i] with digit sum divisible by K. Can you answer each in O(1) after O(N log N) preprocessing?"</td><td>Precompute prefix A[x] = count in [0, x] for bounded x. For large R up to 10^18: digit DP is O(18 &times; K) per query &mdash; effectively O(1). For truly online with 10&#8313; queries: batch process; DP tables for specific K precomputed once; f(R) &minus; f(L&minus;1) is O(1) per query.</td></tr>\n'
NEW += '                        <tr><td class="num-cell">10</td><td>Beyond Stage 5</td><td>"An adversary generates queries to maximise computation. What is optimal strategy, and defence?"</td><td>Adversary: choose large K (maximising mod state) or numbers keeping tight=true long (minimising memo reuse). Defence: meet-in-the-middle for large K. Note: tight=true has only O(digits) paths regardless of memoisation &mdash; adversary cannot make it worse than O(n) per query. O(n &times; K) is the true worst case.</td></tr>\n'
NEW += '                        </tbody>\n'
NEW += '                    </table></div>\n'
NEW += '                    <div class="sec-title">3-Phase Mastery Plan</div>\n'
NEW += '                    <div class="info-box" style="line-height:1.75">\n'
NEW += '                        <strong>Phase 1 &mdash; Solve (strictly by Stage):</strong><br>\n'
NEW += '                        <strong>Stage 1 &mdash; Mechanical frame + f(R) &minus; f(L&minus;1):</strong><br>\n'
NEW += '                        Order: S.No 2 (CSES Counting Numbers), S.No 1 (LC 2999), S.No 4 (LC 357).<br>\n'
NEW += '                        Rule: do NOT use any existing template. Write DFS from scratch with a comment on every variable.<br><br>\n'
NEW += '                        <strong>Stage 2 &mdash; One new dim + leading_zero interaction:</strong><br>\n'
NEW += '                        Order: S.No 3 (LC 233 tuple return), S.No 5 (LC 1012 complement), S.No 6 (LC 2376 canonical 4-component), S.No 8 (LC 600 binary), S.No 9 (LC 902 variable digit set).<br><br>\n'
NEW += '                        <strong>Stage 3 &mdash; Two simultaneous state dims:</strong><br>\n'
NEW += '                        Order: S.No 7 (CF 1073E sum+set), S.No 10 (CF 55D dynamic LCM &rarr; 2520 compression), S.No 12 (LC 2827 balance+mod), S.No 15 (ABC 228 F binary + two constraints).<br><br>\n'
NEW += '                        <strong>Stage 4 &mdash; Hidden digit DP; train recognition reflex:</strong><br>\n'
NEW += '                        For EACH, first write "This IS digit DP because ___" before coding. If you can\'t in 30s, re-read Stage 4.<br>\n'
NEW += '                        S.No 13 (LC 1397 KMP + digit DP), S.No 16 (LC 2719 two tight flags), S.No 19 (CF 1286F two-variable XOR).<br><br>\n'
NEW += '                        <strong>Stage 5 &mdash; Optimisation:</strong><br>\n'
NEW += '                        S.No 23 (Custom matrix exp) &mdash; implement 10&times;10 transition matrix from scratch; verify for n=1,2,3 by hand.<br>\n'
NEW += '                        S.No 11 (LC 1067 digit count) &mdash; verify positional contribution formula analytically before DP.<br><br>\n'
NEW += '                        <strong>Phase 2 &mdash; Drill:</strong><br>\n'
NEW += '                        &bull; <strong>10-minute drill (Stage 1):</strong> Given N (spoken), write digit array extraction + bare (pos, tight) DFS in 2 min. Add one constraint in 3 more min. Target: full Stage 1 in 10 min.<br>\n'
NEW += '                        &bull; <strong>State-design drill (Stage 2&ndash;3):</strong> Given problem description, write ONLY state tuple + terminal acceptance. No code. 3 min per problem. Do 10 problems across Groups 1&ndash;5 before coding any. Builds "state first, code second" reflex.<br>\n'
NEW += '                        &bull; <strong>Identification drill (Stage 4):</strong> From titles only: "Count strings in [s1, s2] with no repeated chars" &rarr; digit DP on strings, base = alphabet, tight = lex, extra = bitmask. "Count pairs (a, b) with a XOR b &le; K" &rarr; two-variable binary digit DP.<br>\n'
NEW += '                        &bull; <strong>Complement drill:</strong> For every "at least one / at least K / contains X" problem, write: answer = total &minus; f_without_X. Verify complement always valid.<br><br>\n'
NEW += '                        <strong>Phase 3 &mdash; Validate (unseen sources):</strong><br>\n'
NEW += '                        &bull; Stage 1: SPOJ NUMTSN &mdash; integers where digits divide the number<br>\n'
NEW += '                        &bull; Stage 2: LightOJ 1205 &mdash; digits read same rotated by 1<br>\n'
NEW += '                        &bull; Stage 3: Codeforces 814D &mdash; game states via digit-DP-style counting<br>\n'
NEW += '                        &bull; Stage 4: Codeforces 1290C &mdash; lex-bound prefix constraints<br>\n'
NEW += '                        &bull; Stage 5: Codeforces 1081G &mdash; matrix exponentiation of digit DP transition matrix for n &le; 10&#8313;\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Graduation Test</div>\n'
NEW += '                    <div class="core-box">\n'
NEW += '                        <strong>Problem 1 &mdash; LC 1397 Find All Good Strings (Stage 3 + Stage 4)</strong><br>\n'
NEW += '                        <em>Stages tested:</em> Stage 4 (string digit DP + KMP) + Stage 3 (two tight flags + KMP state).<br>\n'
NEW += '                        <em>Summary:</em> Count strings of length n in lex range [s1, s2] NOT containing evil substring p. Output mod 10&#8313; + 7.<br>\n'
NEW += '                        <em>Why it proves mastery:</em> Stage 1&ndash;2 candidate cannot encode KMP state. Stage 3-only misses the recognition that strings-in-range = digit DP (Stage 4). Two-tight-flag implementation adds another hurdle. All three stages must be simultaneously active and correctly implemented. Solving in 45 minutes certifies the full recognition-expansion-implementation pipeline.<br><br>\n'
NEW += '                        <strong>Problem 2 &mdash; CF 55D Beautiful Numbers (Stage 3 + Stage 4)</strong><br>\n'
NEW += '                        <em>Stages tested:</em> Stage 4 (non-obvious state compression via LCM) + Stage 3 (two simultaneous modular constraints).<br>\n'
NEW += '                        <em>Summary:</em> Count integers in [L, R] divisible by each of their own non-zero digits.<br>\n'
NEW += '                        <em>Why it proves mastery:</em> Two non-obvious reductions: (1) dynamic LCM compresses to 48 divisors of 2520 (requires knowing lcm(1..9)=2520); (2) number\'s value mod 2520 is sufficient to check divisibility by any digit (since every digit divides 2520). Blindly applying the template builds an unbounded-state DP. Solving cold in 45 min proves deriving state compressions under pressure.<br><br>\n'
NEW += '                        <strong>Problem 3 &mdash; LC 2719 Count of Integers (Stage 3 + Stage 4 + Stage 5 reflex)</strong><br>\n'
NEW += '                        <em>Stages tested:</em> Stage 4 (two tight flags &mdash; string bounds) + Stage 3 (digit sum tracking) + Stage 5 reflex (recognise na&iuml;ve f(R) &minus; f(L&minus;1) is tricky for string-encoded numbers).<br>\n'
NEW += '                        <em>Summary:</em> Given string num1, num2 and min_sum, max_sum, count x in [num1, num2] with digit sum in [min_sum, max_sum].<br>\n'
NEW += '                        <em>Why it proves mastery:</em> Stage 1&ndash;2 candidate tries f(num2) &minus; f(num1&minus;1) and gets stuck computing string decrement of "1000...0". Stage 3 adds digit_sum but still struggles with string lower bound. Only a candidate internalising Stage 4 (two tight flags eliminate the lower-bound decrement problem) solves cleanly. Stage 5 reflex &mdash; a technique that seems to ADD complexity actually REDUCES it &mdash; is the final differentiator.\n'
NEW += '                    </div>\n'
NEW += '                </div>\n'
NEW += '            </div>'

# ------------------------------------------------------------------
OLD = '<div class="topic-card" id="tp39"><div class="coming">Content for Digit DP is coming soon.<br><br>Covers: Count numbers with digit sum = k, Count numbers without repeated digits, Numbers with even number of digits, Digit DP template (tight/free bounds), Non-decreasing digits, At most N given digit set &amp; more.</div></div>'

path = r'E:\PracticeProjec\dsalgofrog\src\pages\index.astro'
content = open(path, encoding='utf-8').read()

if OLD not in content:
    sys.stderr.write('ERROR: tp39 placeholder not found!\n')
    idx = content.find('Content for Digit DP')
    if idx >= 0:
        sys.stderr.write('Found partial at char %d: %r\n' % (idx, content[idx-50:idx+60]))
    sys.exit(1)

content = content.replace(OLD, NEW, 1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

sys.stderr.write('Done: tp39 replaced successfully. New length: %d chars.\n' % len(content))
