# -*- coding: utf-8 -*-
# Part 2: appends Pattern Recognition through Graduation Test + performs file replacement

import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Load part 1 NEW string
from insert_tp38 import NEW

NEW += '                    <div class="sec-title">Pattern Recognition Triggers</div>\n'
NEW += '                    <div class="info-box" style="line-height:1.75">\n'
NEW += '                        <strong>Linguistic Triggers:</strong><br>\n'
NEW += '                        &bull; "for each node, find the [max/min/count] in its subtree" &rarr; Stage 1 bottom-up; dp[v] = f(dp[children]); O(n)<br>\n'
NEW += '                        &bull; "select subset of nodes, no two adjacent, maximise total value" &rarr; Stage 2 MIS tree DP; dp[v][0/1]; O(n)<br>\n'
NEW += '                        &bull; "find the answer for every possible root" &rarr; Stage 2 rerooting DP; two-pass DFS; O(n)<br>\n'
NEW += '                        &bull; "select exactly K nodes/edges from the tree maximising [objective]" &rarr; Stage 3 tree knapsack; dp[v][k]; O(n&sup2;)<br>\n'
NEW += '                        &bull; "count paths with sum / XOR / property P in a tree" &rarr; Stage 3 prefix-sum hashmap on DFS OR centroid decomp; O(n) or O(n log n)<br><br>\n'
NEW += '                        <strong>Structural Triggers:</strong><br>\n'
NEW += '                        &bull; Input is a parent array parent[i]; answer for each node depends on its subtree &rarr; rooted tree DP; post-order; O(n)<br>\n'
NEW += '                        &bull; Answer requires combining TWO arms at a node (diameter, max path sum) &rarr; top-2 arm tracking; global updated at bend; return single arm<br>\n'
NEW += '                        &bull; Multiple queries on subtrees of a static tree &rarr; Euler tour linearisation + BIT/segment tree; O(log n) per query<br><br>\n'
NEW += '                        <strong>Constraint Triggers:</strong><br>\n'
NEW += '                        &bull; n &le; 10&sup5; and "select k nodes from tree" &rarr; O(n&sup2;) tree knapsack may TLE; consider small-to-large for O(n log n)<br>\n'
NEW += '                        &bull; Multiple queries each specifying k "key" nodes on large tree &rarr; virtual tree per query; O(k log n) compressed tree<br><br>\n'
NEW += '                        <strong>Anti-Triggers:</strong><br>\n'
NEW += '                        &bull; "find shortest paths between every pair" &rarr; NOT tree DP &rarr; LCA + binary lifting for single-pair O(log n); BFS from each node O(n&sup2;)<br>\n'
NEW += '                        &bull; "minimum cost to connect all nodes" &rarr; NOT tree DP &rarr; MST (Kruskal/Prim); tree DP assumes tree is GIVEN<br>\n'
NEW += '                        &bull; "number of BSTs with n nodes" &rarr; NOT actual tree DP &rarr; 1D Catalan number DP; no tree traversed\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Decision Framework</div>\n'
NEW += '                    <div class="info-box">\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0;font-size:.78rem"><code>Q1: Is the input an explicit tree (n nodes, n-1 edges)?\n'
NEW += '  YES: Continue to Q2.\n'
NEW += '  NO:  Implicit tree? (BST insertion? Interval containment? Dependency DAG? Parent array?)\n'
NEW += '       If YES: extract the tree (Stage 4), then proceed.\n'
NEW += '       If NO: not a tree DP problem.\n'
NEW += '\n'
NEW += 'Q2: Does the answer at each node depend ONLY on its subtree?\n'
NEW += '  YES: Pure bottom-up tree DP. Stage 1. O(n).\n'
NEW += '       dp[v] = scalar. Recurrence: dp[v] = f(dp[c], val[v]).\n'
NEW += '  NO:  Continue.\n'
NEW += '\n'
NEW += 'Q3: Does the answer change if the root changes?\n'
NEW += '  YES: Rerooting DP. Stage 2. O(n).\n'
NEW += '       First pass: bottom-up (subtree aggregates + sizes).\n'
NEW += '       Second pass: top-down (contribution from above).\n'
NEW += '  NO:  Continue.\n'
NEW += '\n'
NEW += 'Q4: Is there a BINARY CHOICE at each node?\n'
NEW += '    (Include/exclude, covered/not covered, camera/no camera)\n'
NEW += '  YES: Two-state or three-state tree DP. dp[v][s]. Stage 2-3.\n'
NEW += '       2 states: dp[v][0/1].  3+ states: draw state machine FIRST.\n'
NEW += '  NO:  Continue.\n'
NEW += '\n'
NEW += 'Q5: Is there a BUDGET (select exactly K nodes/edges)?\n'
NEW += '  YES: Tree knapsack. dp[v][k]. Stage 3. O(n^2) naive.\n'
NEW += '       Merge children iteratively; O(n^2) by pairs-at-LCA proof.\n'
NEW += '       If n > 10^4: look for Stage 5 optimisation.\n'
NEW += '  NO:  Continue.\n'
NEW += '\n'
NEW += 'Q6: Does the answer involve PATHS (not just subtrees)?\n'
NEW += '  Q6a: Sum/XOR from root to node?\n'
NEW += '       -> Top-down DFS + prefix hashmap. Stage 3. O(n).\n'
NEW += '  Q6b: Max/min over ALL paths?\n'
NEW += '       -> Top-2 arms at each node; global at bend node. Stage 2.\n'
NEW += '  Q6c: COUNT of paths with property?\n'
NEW += '       -> Centroid decomposition. Stage 4. O(n log n).\n'
NEW += '  NO:  Continue.\n'
NEW += '\n'
NEW += 'Q7: Is naive O(n^2) too slow?\n'
NEW += '  -> Knapsack merge -> small-to-large (DSU on tree). O(n log n). Stage 5.\n'
NEW += '  -> Query per node -> Euler tour + BIT. O(n log n). Stage 5.\n'
NEW += '  -> Sparse key-node queries -> Virtual tree. O(k log n)/query. Stage 5.</code></pre>\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">When This Technique Breaks</div>\n'
NEW += '                    <div class="warn-box" style="line-height:1.75">\n'
NEW += '                        &bull; <strong>[Stage 1] Applying bottom-up tree DP when the answer depends on traversal direction:</strong> For "maximum path from any node to any node," a single bottom-up pass misses paths through the root\'s parent. Fix: two-pass rerooting (Stage 2).<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Rerooting with incorrect O(1) transition:</strong> Many candidates write ans[v] = ans[parent] + n &minus; 2&times;sz[parent] (wrong). Fix: always derive by considering which nodes gain/lose distance when re-rooting from parent to v.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Top-2 arms: using the same child for both "up" and "down" arm:</strong> When v IS the best-arm child of parent, the up-contribution must use the second-best arm. Fix: precompute best1[parent] and best2[parent] by index.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Claiming O(n&sup2;) per node for tree knapsack instead of O(n&sup2;) globally:</strong> Correct analysis via pairs-at-LCA gives O(n&sup2;) globally. Each pair (u, w) contributes O(1) at exactly their LCA.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Path DP: forgetting to BACKTRACK hashmap on DFS return:</strong> Missing hashmap[prefix] &minus;= 1 after processing children causes paths from unrelated subtrees to be counted.<br>\n'
NEW += '                        &bull; <strong>[Stage 4] Applying tree DP when input contains cycles:</strong> Post-order invariant breaks for graphs. Fix: verify input is acyclic before applying.<br>\n'
NEW += '                        &bull; <strong>[Stage 5] Small-to-large when merge is NOT associative/commutative:</strong> For aggregates like median, merging doesn\'t directly work. Fix: check associativity before applying.\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Proof of Correctness Skeleton</div>\n'
NEW += '                    <div class="core-box">\n'
NEW += '                        <strong>Stage 1 &mdash; Tree Diameter via Post-Order DFS</strong><br>\n'
NEW += '                        <em>Claim:</em> diameter = max over all nodes v of (top1_arm[v] + top2_arm[v]).<br>\n'
NEW += '                        <em>Proof:</em> Every path has a unique bend node (its LCA). At bend node v: path = arm into one child + arm into another = top1 + top2. Post-order DFS visits every node once as a potential bend. Since every path bends at exactly one node, the global maximum is the true diameter. &#9633;<br><br>\n'
NEW += '                        <strong>Stage 2 &mdash; Rerooting DP Correctness (Sum of Distances)</strong><br>\n'
NEW += '                        <em>Claim:</em> ans[v] = ans[parent(v)] + n &minus; 2&times;sz[v].<br>\n'
NEW += '                        <em>Proof:</em> Re-rooting from p to v: sz[v] nodes get 1 closer; n &minus; sz[v] nodes get 1 farther. Change = (n &minus; sz[v]) &minus; sz[v] = n &minus; 2&times;sz[v]. ans[root] is correct from first pass; each re-root derives from a correct parent; by induction all ans[v] are correct. &#9633;<br><br>\n'
NEW += '                        <strong>Stage 5 &mdash; Tree Knapsack Total Complexity O(n&sup2;)</strong><br>\n'
NEW += '                        <em>Claim:</em> Merge cost O(|accumulated| &times; |child|) totals O(n&sup2;) across all merges.<br>\n'
NEW += '                        <em>Proof:</em> For any pair (u, w), they contribute to exactly ONE merge at their LCA. There are at most C(n,2) pairs. Total cost = &sum; (size_A &times; size_B) = &sum; 1 over all pairs &le; C(n,2) = O(n&sup2;). &#9633;\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Implementation Pitfalls (Code-Level)</div>\n'
NEW += '                    <div class="warn-box">\n'
NEW += '                        <strong>Bug 1 &mdash; Diameter: returning sum of both arms to parent</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>return l + r + node.val   # BUG: parent receives full diameter\nreturn max(l, r) + node.val  # FIX: single best arm</code></pre><br>\n'
NEW += '                        <strong>Bug 2 &mdash; MIS: dp[v][0] not allowing children to be either state</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>dp[v][0] = sum(dp[c][0] for c in ch)                # BUG\ndp[v][0] = sum(max(dp[c][0], dp[c][1]) for c in ch) # FIX</code></pre><br>\n'
NEW += '                        <strong>Bug 3 &mdash; Rerooting: using parent\'s subtree size</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>ans[v] = ans[parent] + n - 2 * sz[parent]  # BUG\nans[v] = ans[parent] + n - 2 * sz[v]       # FIX</code></pre><br>\n'
NEW += '                        <strong>Bug 4 &mdash; Top-2 arms: using same child for both arms</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code># FIX: precompute best1_child and best2_child per parent\nif best1_child[p] == v:\n    up[v] = max(up[p], down[best2_child[p]]) + 1\nelse:\n    up[v] = max(up[p], down[best1_child[p]]) + 1</code></pre><br>\n'
NEW += '                        <strong>Bug 5 &mdash; Three-state camera: null treated as "covered"</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>if not node: return (0, 0, 0)               # BUG\nif not node: return (0, float(\'inf\'), 0)    # FIX: null can\'t have camera</code></pre><br>\n'
NEW += '                        <strong>Bug 6 &mdash; Prefix hashmap path count: missing backtrack</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>hashmap[prefix] = hashmap.get(prefix, 0) + 1\nfor child in node.children:\n    dfs(child, prefix + child.val)\n# BUG: missing backtrack\nhashmap[prefix] -= 1  # FIX</code></pre><br>\n'
NEW += '                        <strong>Bug 7 &mdash; Tree knapsack: full n+1 sized arrays per node</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>dp = [[0] * (n+1) for _ in range(n+1)]  # BUG: O(n^2) space\n# FIX: dp[v] has size sz[v]+1; discard child DPs after merge</code></pre><br>\n'
NEW += '                        <strong>Bug 8 &mdash; Small-to-large: iterating the LARGER set</strong><br>\n'
NEW += '                        <pre style="white-space:pre-wrap;margin:.4rem 0"><code>for elem in large: small.add(elem)          # BUG: O(n) moves\nif len(a) < len(b): a, b = b, a            # FIX: ensure a is larger\nfor elem in b: a.add(elem)                 # FIX: iterate smaller</code></pre>\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Red Flags / Common Mistakes</div>\n'
NEW += '                    <div class="warn-box" style="line-height:1.75">\n'
NEW += '                        &bull; <strong>[Stage 1] Treating the tree as a linear array and applying 1D DP:</strong> BFS level-order DP loses the parent-child relationship. In tree DP the "index" is a node, and transitions go children &rarr; parent.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Forgetting top-2 arms optimisation in rerooting:</strong> O(n) scan over siblings gives O(n&sup2;) total. Precompute best1[v] and best2[v] by index for O(1) per child.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Space is also O(n&sup2;) if child DPs aren\'t discarded:</strong> Time is O(n&sup2;) by pairs-at-LCA, but keeping all arrays makes space O(n&sup2;). Discard child DP after merge; space = O(n).<br>\n'
NEW += '                        &bull; <strong>[Stage 4] Applying tree DP to implicit tree without verifying structure:</strong> Verify the extraction with a small example before coding DP.<br>\n'
NEW += '                        &bull; <strong>[Stage 2] Rerooting: recomputing subtree sizes in second pass:</strong> Subtree sizes are defined relative to the original root. The second DFS reads stored values; never recomputes structure.<br>\n'
NEW += '                        &bull; <strong>[Stage 5] Confusing DSU on tree with Union-Find DSU:</strong> "DSU on tree" = small-to-large merging. Union-Find = path-compressed connected components. Completely different algorithms with the same acronym.<br>\n'
NEW += '                        &bull; <strong>[Stage 3] Not initialising count[0] = 1 before DFS for path hashmap:</strong> count[0] = 1 represents the "empty prefix." Missing this causes root-starting paths to be skipped.\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Interviewer Follow-Up Questions</div>\n'
NEW += '                    <div class="tbl-wrap"><table>\n'
NEW += '                        <thead><tr><th>#</th><th>Stage Push</th><th>Question</th><th>Intended Answer Direction</th></tr></thead>\n'
NEW += '                        <tbody>\n'
NEW += '                        <tr><td class="num-cell">1</td><td>Stage 2</td><td>"Your House Robber III solution uses dp[v][0/1]. What if you could rob at most K consecutive non-adjacent nodes on any root-to-leaf path?"</td><td>Add run-length dimension: dp[v][s][r] where r = consecutive selections ending at v; transitions check r &le; K before allowing s=1; still O(n &times; K)</td></tr>\n'
NEW += '                        <tr><td class="num-cell">2</td><td>Stage 2</td><td>"What if nodes in House Robber III have negative values? Does the algorithm change?"</td><td>No structural change; dp[v][0] naturally yields 0 contribution when skipping negative nodes; max() handles omitting negative-value nodes; no third "skip" state needed</td></tr>\n'
NEW += '                        <tr><td class="num-cell">3</td><td>Stage 3</td><td>"Extend Sum of Distances to: for each node v, find the sum of SQUARED distances to all other nodes."</td><td>Compute cnt[v] and sumD[v] bottom-up; rerooting: ansQ[v] = ansQ[par] + 2&middot;ans[par] + (n &minus; 2&middot;sz[v]); derive by expanding (d+1)&sup2; and (d&minus;1)&sup2;; requires ans[v] already computed</td></tr>\n'
NEW += '                        <tr><td class="num-cell">4</td><td>Stage 3</td><td>"How do you count paths with sum = K in a weighted tree where edge weights can be NEGATIVE?"</td><td>Algorithm is IDENTICAL; negative weights do NOT break correctness because hashmap keys are exact prefix sums; what changes: prefix sums are no longer monotone, so two-pointer fails &mdash; hashmap handles this perfectly</td></tr>\n'
NEW += '                        <tr><td class="num-cell">5</td><td>Stage 4</td><td>"You need to run House Robber DP 10&sup5; times on the same tree, each query marks one node as \'forced included\'. Can you avoid re-running?"</td><td>Precompute dp[v][0/1] bottom-up and up_dp[v][0/1] top-down; combine in O(1) per query; reduces 10&sup5; &times; O(n) to O(n log n) preprocessing + O(log n) per query</td></tr>\n'
NEW += '                        <tr><td class="num-cell">6</td><td>Stage 4</td><td>"Given a tree with node colours, query (u, v, c): count nodes of colour c on the path from u to v. How for 10&sup5; queries?"</td><td>Offline: sort queries by colour; Euler tour + BIT tracks colour contributions; path(u,v) = prefix(u) + prefix(v) &minus; 2&times;prefix(LCA) &minus; val(LCA); O((n + q) log n)</td></tr>\n'
NEW += '                        <tr><td class="num-cell">7</td><td>Stage 5</td><td>"Your tree knapsack is O(n&sup2;). How do you bring it to O(n log&sup2; n)?"</td><td>Small-to-large set merging: each element moves O(log n) times &times; O(log n) per insertion = O(n log&sup2; n); alternatively for path-graph (degenerate tree), 1D knapsack solvable in O(n log n) with divide-and-conquer; for general trees: merge at each centroid takes O(sz log sz)</td></tr>\n'
NEW += '                        <tr><td class="num-cell">8</td><td>Stage 5</td><td>"10&sup5; queries each specify k &le; 20 key nodes. For each query, run a tree DP counting only nodes reachable from key nodes. How to avoid O(n) per query?"</td><td>Virtual tree: build compressed tree on k key nodes in O(k log n) using Euler tour order + pairwise LCA; O(k) nodes; run tree DP in O(k); total O(q &times; k log n) instead of O(q &times; n)</td></tr>\n'
NEW += '                        <tr><td class="num-cell">9</td><td>Beyond Stage 5</td><td>"The tree is DYNAMIC &mdash; edges can be added or removed; after each update you need the new diameter. How do you maintain this in sub-O(n) per update?"</td><td>Link-Cut Tree (LCT): each path query is O(log n); maintain diameter using two "farthest node from root" queries after each structural update; O(log&sup2; n) per update amortised</td></tr>\n'
NEW += '                        <tr><td class="num-cell">10</td><td>Beyond Stage 5</td><td>"You have a distributed system where each server holds one subtree of a large tree with n = 10&sup9; nodes. How would you compute the tree diameter across servers?"</td><td>Each server computes local diameter AND two deepest arms from its subtree root; combine across servers: diameter = max(local diameters, arm1[server_A] + arm1[server_B] + 1 for all adjacent server pairs); O(servers &minus; 1) messages</td></tr>\n'
NEW += '                        </tbody>\n'
NEW += '                    </table></div>\n'
NEW += '                    <div class="sec-title">3-Phase Mastery Plan</div>\n'
NEW += '                    <div class="info-box" style="line-height:1.75">\n'
NEW += '                        <strong>Phase 1 &mdash; Solve (strictly by Stage):</strong><br>\n'
NEW += '                        <strong>Stage 1 &mdash; Establish the post-order invariant:</strong><br>\n'
NEW += '                        Solve in this exact order: S.No 2 (Path Sum III), S.No 1 (Diameter), S.No 4 (Distribute Coins), S.No 5 (Longest ZigZag).<br>\n'
NEW += '                        After these four: given ANY single-pass tree DP problem, you must be able to state the return signature (val1, val2, ...) and global update formula before touching code. Time target: 10 min each.<br><br>\n'
NEW += '                        <strong>Stage 2 &mdash; Add binary choice and rerooting:</strong><br>\n'
NEW += '                        Solve in order: S.No 3 (House Robber III), S.No 6 (Longest Path Different Adjacent Values), S.No 9 (Sum of Distances), S.No 10 (Count Possible Roots), S.No 11 (Max&ndash;Min Price Difference).<br>\n'
NEW += '                        Drill: for rerooting problems, always write the formula derivation (which nodes gain/lose distance) on paper before coding.<br><br>\n'
NEW += '                        <strong>Stage 3 &mdash; State expansion and knapsack:</strong><br>\n'
NEW += '                        Solve in order: S.No 8 (Binary Tree Cameras), S.No 18 (CF 161D Distance in Tree), S.No 29 (USACO Delegation), S.No 13 (Subtree Label Count).<br><br>\n'
NEW += '                        <strong>Stage 4 &mdash; Implicit trees and hidden reductions:</strong><br>\n'
NEW += '                        Solve in order: S.No 14 (Count Nodes Highest Score), S.No 21 (Reorder Array &rarr; Same BST), S.No 22 (Number of Good Paths), S.No 20 (Count Valid Paths &mdash; Centroid).<br><br>\n'
NEW += '                        <strong>Stage 5 &mdash; Optimisation:</strong><br>\n'
NEW += '                        Solve in order: S.No 26 (Lomsat Gelral CF 600E), S.No 32 (Smallest Missing Value), S.No 27 (USACO Sprinklers 2), S.No 31 (AtCoder Virtual Tree).<br><br>\n'
NEW += '                        <strong>Phase 2 &mdash; Drill:</strong><br>\n'
NEW += '                        &bull; 10-min drill (Stage 1): Write DFS signature and global update rule for: height, diameter, max path sum, count paths sum K &mdash; without referencing any solution.<br>\n'
NEW += '                        &bull; Formula drill (Stage 2): Cover the problem; write the rerooting transition formula from scratch for: sum of distances, max arm difference, min height under rerooting. Verify on a 4-node star graph by hand.<br>\n'
NEW += '                        &bull; State machine drill (Stage 3): Draw the state transition diagram for binary tree cameras BEFORE coding. Verify: do null nodes produce state 0, 1, or 2? (Answer: null &rarr; special sentinel; leaf has state 0).<br>\n'
NEW += '                        &bull; Knapsack merge drill: Trace the tree knapsack merge for a 3-node path (root &rarr; child &rarr; grandchild) with budget k=2. Verify the pairs-at-LCA argument by listing all pairs and their LCA.<br>\n'
NEW += '                        &bull; Implicit tree drill (Stage 4): For S.No 21 and S.No 22: cover the code; state the tree-extraction step in one sentence before writing any DP.<br><br>\n'
NEW += '                        <strong>Phase 3 &mdash; Validate (unseen problem sources):</strong><br>\n'
NEW += '                        &bull; Stage 1: USACO Silver 2020 Feb "Swapity Swapity Swap" &mdash; subtree tracking under repeated permutation<br>\n'
NEW += '                        &bull; Stage 2: Codeforces Round 604 Div 1 C "Beautiful Regional Contest" &mdash; rerooting with conditional edge weights<br>\n'
NEW += '                        &bull; Stage 3: AtCoder Educational DP Contest V "Subtree" &mdash; two-state tree DP with connectivity constraint<br>\n'
NEW += '                        &bull; Stage 4: Codeforces Edu Round 67 F "Hive" &mdash; implicit tree from interval structure; tree DP on containment tree<br>\n'
NEW += '                        &bull; Stage 5: USACO Platinum 2019 Feb "Mowing the Field" &mdash; virtual tree on sparse key nodes with path DP\n'
NEW += '                    </div>\n'
NEW += '                    <div class="sec-title">Graduation Test</div>\n'
NEW += '                    <div class="core-box">\n'
NEW += '                        <strong>Problem 1 &mdash; "Balanced Forest Partition" (Stage 3 + Stage 4)</strong><br>\n'
NEW += '                        <em>Source:</em> IOI 2017 / Codeforces 901C<br>\n'
NEW += '                        <em>Stages tested:</em> Stage 4 (implicit tree) + Stage 3 (tree knapsack)<br>\n'
NEW += '                        <em>Summary:</em> Given a tree where each node has a value, determine if you can remove exactly one edge to create two components with equal sum. If not, determine if you can add one node (with a chosen value) to make such a partition possible after one edge cut.<br>\n'
NEW += '                        <em>Why it proves mastery:</em> A candidate who only knows Stage 1&ndash;2 computes total sum and checks each subtree &mdash; solves the basic version. The full problem requires recognising "achievable subtree sums" as a tree knapsack (Stage 3) AND that the added node can be placed anywhere (Stage 4 rerooting of the knapsack). No single stage is sufficient; all four must interoperate. Solving cold in 45 minutes certifies internalisation of both patterns.<br><br>\n'
NEW += '                        <strong>Problem 2 &mdash; "CF 1188E" Tree Isomorphism Counting (Stage 3 + Stage 5)</strong><br>\n'
NEW += '                        <em>Source:</em> Codeforces 1188E<br>\n'
NEW += '                        <em>Stages tested:</em> Stage 5 (small-to-large) + Stage 3 (multi-dimensional state DP)<br>\n'
NEW += '                        <em>Summary:</em> Given a tree with nodes coloured red or blue and edge weights, find the minimum weight set of edges to remove such that every resulting component has equal numbers of red and blue nodes.<br>\n'
NEW += '                        <em>Why it proves mastery:</em> Candidate must (1) recognise balance = (red &minus; blue) is the DP dimension, (2) derive correct merge: new_balance = balance_so_far + balance_child at cost 0 (keep) or (edge_weight &minus; dp[child]) (cut), and (3) apply small-to-large to reduce O(n&sup2;) to O(n log n). All three realisations must arrive in sequence under time pressure.<br><br>\n'
NEW += '                        <strong>Problem 3 &mdash; "Maximum XOR Path in Tree with K Updates" (Stage 4 + Stage 5)</strong><br>\n'
NEW += '                        <em>Source:</em> Custom adaptation of CF 571D + trie-on-tree<br>\n'
NEW += '                        <em>Stages tested:</em> Stage 4 (XOR path transformation) + Stage 5 (trie as per-centroid data structure)<br>\n'
NEW += '                        <em>Summary:</em> Given a weighted tree, answer q queries: "What is the maximum XOR of values on any path in the tree?" After each query, one edge weight is updated.<br>\n'
NEW += '                        <em>Why it proves mastery:</em> Three independent insights must all arrive: (1) XOR path = XOR of two root-to-node prefixes (Stage 4 reduction); (2) maximum XOR over all pairs = trie query (Stage 5 data structure); (3) updates require centroid decomposition to localise change to O(log n) centroids (Stage 5 decomposition). Missing any one makes the problem unsolvable. Solving cold certifies mastery of the full staircase.\n'
NEW += '                    </div>\n'
NEW += '                </div>\n'
NEW += '            </div>'

# ------------------------------------------------------------------
OLD = '<div class="topic-card" id="tp38"><div class="coming">Content for Tree DP is coming soon.<br><br>Covers: House Robber III (tree), Diameter of Binary Tree, Binary Tree Cameras, Maximum Path Sum, Count Nodes Equal to Average of Subtree, Longest Path with Same Values, Rerooting technique, Tree Knapsack &amp; more.</div></div>'

path = r'E:\PracticeProjec\dsalgofrog\src\pages\index.astro'
content = open(path, encoding='utf-8').read()

if OLD not in content:
    print('ERROR: placeholder not found!')
    print('Searching partial...')
    idx = content.find('Content for Tree DP is coming')
    if idx >= 0:
        print('Found at char', idx, '| snippet:', repr(content[idx-50:idx+60]))
    sys.exit(1)

content = content.replace(OLD, NEW, 1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print('Done: tp38 replaced successfully.')
